
package MernisServiceReference;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.0.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 5A3202B4B674BD54F4D28482BD36CCE1BABACB41774D757CFC7EFBDDBE256DA3F3BA30D13D296D0DBB6173E313585ADAC7C36E460D752B77F9DA4A55AA4362B5
//------------------------------------------------------------------------
import java.util.HashMap;
import java.util.Map;
import java.util.List;



public class PGNResponseData
{
    private HashMap< String,String> headers = new HashMap< String,String>();
    private String body;

    public HashMap< String,String> getHeaders()
    {
        return headers;
    }
    
    public String getBody()
    {
        return body;
    }

    public void setBody(String body)
    {
        this.body=body;
    }
}